# The template for this GNUPlot script was initially generated by an LLM

# Set output to a PNG image
set terminal png size 800,600
set output filename

# Set titles and labels
set title "Comparison of Calculated and Actual Ground Steering"
set xlabel "Time (seconds)"
set ylabel "Steering Angle"

# Set grid
set grid

# Define the data delimiter
set datafile separator ","

# Set x-axis data type as time
set xdata time
set timefmt "%s"  # GNUplot reads time in seconds since epoch
set format x "%H:%M:%S"  # Show hours, minutes, seconds

# Set autoscaling
set autoscale

set label "group 21" at graph 0.6, graph 0.6 front tc rgb "black"

# Plots the data converting timestamps to seconds for proper scaling
plot "/tmp/plotting_data.csv" using ($1/1000000.0):2 with lines title 'Calculated Steering Angle' lc rgb 'red', \
     "/tmp/plotting_data.csv" using ($1/1000000.0):3 with lines title 'Actual Ground Steering' lc rgb 'blue'

